name: godot-ci
on:
  push:
    branches: [ main ]
env:
  GODOT_VERSION: 3.5.3
jobs:
  jumpy-game:
    runs-on: ubuntu-25.10
    permissions: write
  name: Export game
  steps:
    -  name: Checkout source code
       uses: actions/checkout@v3

    -  name: Godot Export
       id: export
       uses: firebelley/godot-export@v7.0.0
       with:
          godot_executable_download_url: "https://downloads.godotengine.org/?version=3.5.3&flavor=stable&slug=x11.64.zip&platform=linux.64"
       cache: true
     env:
    -  name: create release
       uses: ncipollo/release-action@v1.18.0
       with:
         token: ${{secrets.GH_TOKEN}}
         generateReleaseNotes: true
         tag: v2.0.0
         artifacts: ${{steps.export.outputs.archive_directory}}/*
